version: 2

jobs:
  build:
    docker:
      - image: dadamssg/7.3.3-php-fpm:0.0.1
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - composer-v3-{{ checksum "composer.lock" }}
            - composer-v3-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v3-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: php bin/phpunit
      - run:
          name: install docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dadamssg/360guestbook-test:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push dadamssg/360guestbook-test:$TAG
